hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - model: simple_model
  - train_param: params
  - _self_
data:
  raw: ../data/raw/Emotions-Dataset/
  result: ../data/result

models:
  final_chp: ../model/final.pt